backstage:
  serviceAccount:
    create: true
    name: backstage
  backstage:
    image:
      repository: ghcr.io/my-silly-organisation/backstage
      tag: 1.31.2
    extraEnvVarsSecrets:
      - backstage-secrets
    extraEnvVars:
      - name: NODE_ENV
        value: development
      - name: ARGOCD_URL
        value: "http://argocd.74.220.21.243.nip.io/api/v1/"
      - name: BASE_URL
        value: "backstage.74.220.21.243.nip.io"
      - name: CATALOG_LOCATION
        value: "https://github.com/dirien/backstage-demo/blob/main/catalog/catalog-all.yaml"
      - name: POSTGRES_HOST
        value: "backstage-rw"
      - name: POSTGRES_PORT
        value: "5432"
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
  ingress:
    enabled: true
    className: ""
    host: "backstage.74.220.21.243.nip.io"
